# Simple service config
spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    # Main static gateway configuration
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
# Exposing port
server:
  port: 8888

logging:
  level:
    org.springframework.cloud.gateway: DEBUG