spring:
  application:
    name: hospital-service
  cloud:
    config:
      discovery:
        enabled: true
      enabled: false # Switch to false if you add config server
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: hospital-service # Specify schema to Hibernate ORM, Mapping ith JPA Entities in Postgres DB
    show-sql: true # Show & Debug SQL request
  liquibase:
    change-log: classpath:db.changelog/2025/db.changelog-master.yaml # Changelog for only this microservice
    default-schema: hospital-service
    enabled: false #TODO: know why I can't fing the yaml changelog on starting application. Mandatory to avoid manual schema creation.

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: 'health refresh'
logging:
  level:
    liquibase: DEBUG # helps to debug database migrations
