spring:

  datasource:
    url: jdbc:h2:mem:test_database;DB_CLOSE_DELAY=-1;
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    properties:
      hibernate:
        default_schema: medhead_hospital_service # Specify the schema name explicitly here
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true # Show & Debug SQL request

  cloud:
    function:
      definition: decrementBedAvailability
    stream:
      bindings:
        decrementBedAvailability-in-0:
          destination: bed-reservation-booked
          group: bed-reservation-consumer-group
          content-type: application/json

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

  liquibase:
    enabled: false  # Desactivate liquibase and preliquibase for faster execution

preliquibase:
  enabled: false

eureka:
  client:
    enabled: false # Disable Eureka during tests

logging:
  level:
    root: INFO                          # Default level for all loggers
    org.springframework.jdbc: WARN      # Avoid SQL statements unless debugging
    org.springframework.boot.context.properties: WARN # Avoid noisy binding logs unless needed
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"